<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpenRA.Platforms.Browser</AssemblyName>
    <RootNamespace>OpenRA.Platforms.Browser</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenRA.Game\OpenRA.Game.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.Fonts" Version="2.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4" />
  </ItemGroup>
</Project>
